### ISSUE TITLE
Implement wit.ai into the messenger app

### ISSUE THREAD

**Issue by gcid12** [six100/accessbot#4]
Wit.ai is already integrated to FB messenger by default, the purpose of this ticket is to create a working example inside the Accessibility-Bot App.  Wit.ai will be used in multiple situations, but the most important is to capture the user request for accessibility:

Intent: 
`request_accessibility_info`
```
"I want to know if {place} place is accessible for {disability}".
```

Entities:
`place` = Restaurant  | Store |  Movie |  Theatre | etc..
`disability` = Wheelchair | Visual impaired | etc.. 

**Desired Outcome: Create a branch and create a conversation that uses wit.ai**

⚠️You will need to be in the developers list to create the WIT app, if you are not yet, please contact @gcid12 here or in the Slack channel.

**Comment by VidhushiniSrinivasan16** [comment]
PR: https://github.com/six100/accessbot/pull/11

**Comment by VidhushiniSrinivasan16** [comment]
done
