### ISSUE TITLE
Define a way to load multiple utterances to Wit.ai

### ISSUE THREAD

**Issue by gcid12** [six100/accessbot#9]
A good way to differentiate our bot and make it more responsive is to train wit.ai properly with multiple utterances targeting the same intents. Wit.ai interface have a way to load one at a time, but there's also a way to load them using the API.

The purpose of this ticket is to define a clear flow to upload multiple utterances at the same time. This utterances can be crowdsourced in different languages in platforms like MechTurk. 

https://wit.ai/docs/http/20200513

**Comment by VidhushiniSrinivasan16** [comment]
PR: https://github.com/six100/accessbot/pull/12

**Comment by VidhushiniSrinivasan16** [comment]
done
